### ISSUE TITLE
Directory structure simplification

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#1]
Can we remove the top Sudoku directory, placing diuf in the root?
This works on my local copy, no path adjustments are required in the code.

**Comment by SudokuMonster** [comment]
Looked into it … Not easy to do from browser …
Needs to be done from command line and may require copying and deleting files
It may be easier to delete the project and re - do it from the start

**Comment by dobrichev** [comment]
Done
