### ISSUE TITLE
Cell.potentialValues size

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#10]
In the actual code the field Cell.potentialValues consists of BitSet(10) with first bit unused.
This doesn't change the behaviour but is confusing and should be fixed even by enlarging the initial size from 9 to 10 or by modify getters and setters to access bit with index (value - 1).
Low priority.

**Comment by 1to9only** [comment]
I don't think this is a worthwhile change.
- BitSet(9) and BitSet(10) are internally implemented as an int array of size 1.
- For readability, bit positions 1-9 represent numbers 1-9.
- Implementing bit index = number - 1 would make it slower!
I left this alone when looking to speed up serate for the patterns game!

**Comment by dobrichev** [comment]
**1to9only**, you are right but positional bitsets are also of size 9 and are zero based. That is confusing.
Maybe, some day, we will go back to this change.
For now, perhaps the best action is updating the comments to reflect reality.

**Comment by dobrichev** [comment]
Fixed in master. Initial size to 10 and clarification in doc that bit 0 is unused. Closing.
