### ISSUE TITLE
you can undo to the previous grid

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#101]
load/paste a grid
solve a few cells (optional)
load/paste another grid
click undo

**Comment by SudokuMonster** [comment]
This appears at 1st glance easy to fix as you need to clear what is the memory trail when you load/paste

**Comment by 1to9only** [comment]
The Undo feature is based on code from https://github.com/Itsukara/SudokuExplainerPlus.
I think I implemented it differently in Sudoku16x16Explainer and other SEs.
If/When time permits, I'll port over the fix.
