### ISSUE TITLE
X-Windoku grid of interest / Rating, solving bug in an X-Windoku

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#111]
This SukakuExplainer (private build, version 1.17.11) solves this X-Windoku **incorrectly**, and chokes up...
```
.......1.....2...3.........4....3.......5...6....1.........78......6........32... ED=20.0/9.4/2.9
23954671851792864368437125942568397197125438686371942535.19786279246513.146832597
```
1to9only's SukakuExplainer rating (private build, version 2021.6.17):
```
.......1.....2...3.........4....3.......5...6....1.........78......6........32... ED=9.6/9.4/2.6
932674518678521943541398267469283751217459386853716429326147895794865132185932674
```
X-Windoku from this m_b_metcalf's post: http://forum.enjoysudoku.com/post309317.html#p309317

**Comment by 1to9only** [comment]
I've looked at SukakuExplainer' solution path, and it goes wrong at step 64:
```
4.3, Grouped 2 Strong links 101: Cell r9c7,r7c9,r7c5,r1c5 on value 4: r1c6<>4
```
It removes candidate 4 from r1c6, when it is the cell solution.

If you disable the 'Skyscraper, Kite, Turbot' solving technique, the X-Windoku solves OK, X-Windoku rating: ED=9.6/9.4/2.6.
From the command line, specify: --techs=1111111111010111011011111011100111100111111111

**Comment by SudokuMonster** [comment]
This bug should really take priority as I can't tell if it has only a limited effect or not. This example aided with the GUI at the incorrect step should highlight where the logic goes wrong and hopefully target the code
