### ISSUE TITLE
Solver chooses Direct Hidden Pair when Naked Single exists

### ISSUE THREAD

**Issue by jdalbey** [SudokuMonster/SukakuExplainer#115]
Hello folks,
I'm a novice Sudoku player using this tool to learn techniques.  I was using the "Solve Step" feature to step through the solution to a puzzle and found a peculiar situation. SE suggested to use "Direct Hidden Pair" when there is an obvious Naked Single on the grid. This doesn't seem very realistic to me because a human would most likely choose the obvious move over the more subtle one. 
Here is the puzzle in question. SE suggests "Cells C3, C3: 1,7 in column" but cell D4 contains a single 9.
![board248](https://user-images.githubusercontent.com/7251133/163918028-6e96cf12-4c5b-4173-9afd-3cafcd58cfdd.png)
Can anyone explain what's going on here? 
Here's the puzzle line if you want to try it out:
`.......71..83......2.......41....6.....87....7........6.3.4.......5..82..........`

**Comment by 1to9only** [comment]
Without pencilmarks it is harder (not impossible!) to spot the Naked Single.
![115 Naked Single r4c4 9](https://user-images.githubusercontent.com/53971101/164992377-bf6dda2e-f520-44f0-b63c-f46410329892.png)

See this wiki page:
https://github.com/SudokuMonster/SukakuExplainer/wiki/Difficulty-Ratings-in-Sukaku-Explainer-v1.17.8
This shows the order SE applies solving techniques, it will search for Direct Hidden Pair before Naked Single.

**Comment by jdalbey** [comment]
Thanks for your explanation.  I guess it's somewhat a matter of personal preference.  When I'm working a paper puzzle without pencil marks Naked Singles are definitely easier for me to find than Hidden Pairs.  So I forked the project and made a modification that some people may find useful.  I removed all the hard-coded parts of the solver that assign the order in which rules are processed and replaced it with code that dynamically loads a properties file with solving techniques and their difficulties.  Now it is possible to "personalize" the difficulty for the rules so the solver will utilize them in an order of your choice, without having to modify the code.  Find it over on [SourceForge]( https://sourceforge.net/p/sukakuexplainer/code/HEAD/tree/tags/release-0.1/).

**Comment by 1to9only** [comment]
@jdalbey 
Interesting changes to the code. It's perfectly fine for your own personal use.

Generally SudokuExplainer/SukakuExplainer (SE) is the de facto (universal!) sudoku rating used at http://forum.enjoysudoku.com/ and on the Patterns Game at http://forum.enjoysudoku.com/interactive-games-f8.html

Also, your Analyzer.java seems to have been copied from the 16x16 version. There is a 9x9 version (Tester.java) at https://github.com/1to9only/SukakuExplainer 

basics.java is my early modification to the original Tester to find sudokus that solves using basic techniques only.
