### ISSUE TITLE
Master branch can't compile on java version prior 10

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#13]
[This branch](https://github.com/SudokuMonster/SukakuExplainer/commit/0a312919d20e82a160b4f3e7cd99327eddb77fbe) by **Sudokuwiki** introduces new syntax _var_ and the master branch (including [release v1.2.1.5](https://github.com/SudokuMonster/SukakuExplainer/releases/tag/v1.2.1.5)) cannot be compiled on java versions prior to 10.
Can we fix this and try writing code compatible with older java 8 version which IMHO is still the mainstream version?

**Comment by SudokuMonster** [comment]
Hopefully this would allow also parsing vanilla sudoku grids similar to this format as well:

. . . | . . . | . . .
2 . . | . . . | . . 9
. . . | 7 5 4 | . . .
---------------------
5 . 4 | . . . | 6 . 1
. 2 . | . . . | . 5 .
. 3 1 | . . . | 4 9 .
---------------------
. . 9 | 8 . 2 | 5 . .
. 5 . | 4 . 6 | . 1 .
. 6 . | 9 7 5 | . 2 .

**Comment by dobrichev** [comment]
OK, but this is shifting the target of the project and also enforces me to clone the repository and work only on my clone without intending to merge the changes back here.
I'm definitely not going to change the java version of my work environment because of this project.

**Comment by SudokuMonster** [comment]
resolving the issue then branching GUI only will not interfere with the command line entry aspect of the project?

**Comment by dobrichev** [comment]
Surely the same functionality can be rewritten in more conventional way.

**Comment by SudokuMonster** [comment]
I'll move ahead and revert. Sudokuwiki's changes are now in the the GUI branch which compiles except under he most recent JAVA release

**Comment by 1to9only** [comment]
Also the 1.2.1.5 SukakuExplainer requires Java Runtime (class file version 56.0) to run JDK-12. I am running with JDK-8. To resolve download and install the latest JDK.

**Comment by SudokuMonster** [comment]
Unfortunately. I tried to revert to the Aug 5 release but ran into issues with SudokuIO.java, something that dobrichev addressed. The resulting fix however, changed how the GUI handles IO. I'm therefore painfully reverting to the latest release again with the 3 files which @sudokuwiki modified appearing. Your earlier request to modify the code in these 3 files to a Java 8 compliant code still holds

**Comment by dobrichev** [comment]
What are the expected next steps?

**Comment by SudokuMonster** [comment]
Possible next steps:
1. accept current state of JAVA compatibility: No action needed directly to Master branch. Your working tools on any branches should be compatible with that level of JAVA
2. change the Master branch directly (3 files sudoku wiki modified + any others) to make it compatible with Java 8. This person should ideally be sudokuwiki but can be anybody with code compatibility knowledge

if step 2 is done … The Master code needs to be tested to check it compiles with JAVA 8 and works. A new release v1.2.1.6 is done & then work resumes on the branches

**Comment by dobrichev** [comment]
Just for fun, I am reading the first option as

> **Don't** accept current state of JAVA compatibility: No action needed **from you** directly to Master branch.

How frequently from now on is expected actions similar to step 2 to appear?

I am asking because I was almost ready to merge my work into the master but now I have to deal with 18 almost identical fixes of the new java reserved word "var", in code that implements functionality not discussed here, being not sure the fixes wouldn't be overwritten soon by a similar commit.

**Comment by SudokuMonster** [comment]
@sudokuwiki only updated these 3 files with a single commit. I'm not sure if he is aware of the compatibility issues that we are discussing. I'm not sure if he is going to do any more collaborating but he hasn't replied to some of the issues raised.

With @1to9only  modifiying the code by proxy as he hasn't collaborated in the repository directly through commits, it will be either me or you who currently modify the code. I will not be modifying the Master JAVA files now unless after a branch pull request is discussed and agreed.

**Comment by dobrichev** [comment]
I've fixed Java 8 compatibility issue in SudokuIO.java.
Also aligned branch parallelChaining to master.

Now I will open a merge request for parallelChaining to master making visible all my changes to master.
After merging (and testing prior or after the merging) to master, I will close this issue.

Please, help in testing because I don't know what to test in GUI.

**Comment by SudokuMonster** [comment]
This is very exciting ... yes absolutely.

We should have a set of puzzles of known ER/EP/ED rating from the patterns game in addition to the known relatively easy Sukakus that we know their rating from 1to9only early modifications. I’ll handle the GUI testing because that is hands on!!

I can prepare the set of puzzles on a wiki page but it may take until midnight GMT to compile

Well done!!

**Comment by sudokuwiki** [comment]
Don't know why var is an issue. But if old java does not accept this, then you could write the full type.
It compiles on my pc, strangely the IDE does not detect for which version it should compile. Sort of no real experience with git/guidelines.

**Comment by sudokuwiki** [comment]
Maybe there could be an extra parser for multiline grid @SudokuMonster mentioned.

**Comment by sudokuwiki** [comment]
Issue can be closed I guess, can someone verify?

**Comment by dobrichev** [comment]
I just verified that some committed on master this breaking the Pull Request.
8 hours ago I asked how frequently similar issues is expected to appear...
