### ISSUE TITLE
Window Title to show Sukaku Explainer

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#15]
This is a cosmetic change to SudokuFrame.java, method initialize():
change this:
this.setTitle("Sudoku Explainer " + VERSION + "." + REVISION + SUBREV);
to:
this.setTitle("Sukaku Explainer " + VERSION + "." + REVISION + SUBREV);

**Comment by 1to9only** [comment]
Please leave this simple change to me, to test my git skills!

**Comment by SudokuMonster** [comment]
Sure but remember you may need to accept the invitation to be able to collaborate
https://github.com/SudokuMonster/SukakuExplainer/invitations

**Comment by SudokuMonster** [comment]
Remember to close this issue when done @1to9only

**Comment by dobrichev** [comment]
... also take a look at the About box ;)
And have in mind that the version string in serate should be abandoned and these versions should be used in batch mode too. I see they are mixture of integers and strings, aren't static, the university is hardcoded by some student, etc.

**Comment by 1to9only** [comment]
This may take me many days to get round to fix, so if a new release is imminent, anyone can feel free to fix this. It's just that I tend to do things my own peculiar way! Also I do other things.
[rant on]I'm doing more testing than developing.[rant off]

**Comment by dobrichev** [comment]
Excellent. My comment above was a suggestion, not a critique ;) All this can be done incrementally.

**Comment by 1to9only** [comment]
ah! i wasn't talking about the about box!!

**Comment by SudokuMonster** [comment]
I'll do the box … and few minor cosmetics because I'm keen on getting the 1.2.1.6 release out. All the heavy lifting and heavy work starts afterwards when we branch out

Changes for this cosmetic change (Fun as I was playing cat and mouse with these things):
```
SukakuFrame.java
313: Sukaku
Setings.java
19: 1.6
Aboutdialog.java
69: 2019
72: Sukaku
94: 2.1
Welcome.html
3: Sukaku
```

**Comment by 1to9only** [comment]
It's a bit of a can of worms!
There are hardcoded version version numbers in serate.java, hints.java, pencilmarks.java - which I've tended to leave asis.
A more general solution is required, e.g. change release number in one file, build, and the same version number appears everywhere!

**Comment by SudokuMonster** [comment]
That should be doable as settings.java appears to have:
```
    public final static int VERSION = 1;
    public final static int REVISION = 2;
    public final static String SUBREV = ".1.6";
```
Which then can be referenced on each occasion
