### ISSUE TITLE
When running GUI, a java.lang.NullPointerException is dumped to console

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#16]
Message is:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
followed by a stack trace.

This is due of one of 4 of these (similar) lines in SudokuIO.java:
ErrorMessage(WARNING_MSG, false, (Object[])null);

This should be changed to:
ErrorMessage(WARNING_MSG, false, (Object[])(new String[0]));

**Comment by SudokuMonster** [comment]
As per previous request by @dobrichev. could we limit any direct changes to Master to above and cosmetic changes mentioned in the other issue. The idea is to have a stable release which we could work on later via branching

**Comment by dobrichev** [comment]
I am taking this. It was reproduced on my machine. Will try **1to9only**'s advice.

And yes, let don't simultaneously make changes in master.
For educational purposes it is better to fork to your branch, do and commit changes there (hoping others don't do many changes at the same files in master), and finally merge your branch to master.

**Comment by dobrichev** [comment]
Source is fixed and committed to master.
Should we replace the jar in latest release or create new now or create new after other possible hotfixes?

**Comment by dobrichev** [comment]
Hope this is fixed in release v1.2.1.6.1 (I didn't check and at the moment can't).
Please check and close this.

**Comment by dobrichev** [comment]
Double checked - it is fixed in the current master. Closing.
