### ISSUE TITLE
The GUI fails to load many common sudoku grid formats

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#17]
Here are some I took from http://forum.enjoysudoku.com.
I've only tried these by pasting from the clipboard.
Only the first grid loaded.

```
12.3.45..
6.......3
....5..2.
5.....7..
..1..6.4.
8...3...9
9..8..1..
..6.7....
.5...9..4 [ok]

 1 2 . 6 . 4 5 . .
 3 . . . . . . . 7
 . . . . 5 . . 2 .
 8 . . . . . 1 . .
 . . 6 . . 2 . 9 .
 4 . . . 9 . . . 5
 6 . . 8 . . 7 . .
 . . 1 . 6 . . . .
 . 4 . . . 5 . . 3 [fail]

 5 4 . | 1 . 3 | 8 . . 
 9 . . | . . . | . . 1 
 . . . | . 5 . | . 4 . 
-------+-------+------
 7 . . | . . . | 2 . . 
 . . 5 | . . 7 | . 9 . 
 1 . . | . 3 . | . . 7 
-------+-------+------
 6 . . | 4 . . | 9 . . 
 . . 7 | . 2 . | . . . 
 . 8 . | . . 1 | . . 6 [fail]

 *-----------*
 |5..|...|...|
 |2..|465|8..|
 |.36|9..|.25|
 |---+---+---|
 |983|6..|...|
 |...|.4.|...|
 |...|..3|679|
 |---+---+---|
 |35.|..6|14.|
 |..2|154|..7|
 |...|...|..8|
 *-----------* [fail]

+-------+-------+-------+
| . 1 . | . . . | . . 2 |
| 3 . . | . . 1 | 4 . . |
| . . . | . 3 . | . 5 . |
+-------+-------+-------+
| . . . | 1 . . | . 6 . |
| . . 5 | . 7 . | 3 . . |
| . 2 . | . . 3 | . . . |
+-------+-------+-------+
| . . 2 | . 4 . | . . . |
| . 8 . | 6 . . | . . 1 |
| 6 . . | . . . | . 7 . |
+-------+-------+-------+ [fail]
```

**Comment by SudokuMonster** [comment]
The update to gui from sudoku wiki allows parsing
1. Pencilmark grid
2. 729-character per line sukaku
3. 81-character vanilla sudoku
4. multi line vanilla sudoku only if it has 81 consecutive characters

The other formats are not supported by gui at this current state of release

**Comment by 1to9only** [comment]
But the previous SudokuIO.java code loaded ALL of them. I think, a warning message with all but the first one!

I think ALL can be pasted into SudokuExplainer, and the Aug 5 SukakuExplainer.

It means I can no longer copy the daily puzzle to clipboard, and directly paste into SukakuExplainer - I have to convert it to 81-chars format first!

**Comment by SudokuMonster** [comment]
I tried Aug 5 sudoku explainer. It will only accept the 729-character line sukaku puzzle. The other formats don't paste into a usable puzzle

**Comment by 1to9only** [comment]
SukakuExplainer came about as quick a hack of SudokuExplainer, and the Aug 5 release was a quick&dirty fix to the APE/ATE issue. The pencilmark grid was not a requirement then!

It's a good thing pencilmark grid is now supported, at the expense of existing functionality - this is code regression!

If the consensus is not to support the many common sudoku formats, then I'll live with it, i.e. not use it for sudokus.

**Comment by SudokuMonster** [comment]
We need the common sudoku formats supported in the GUI. It is where our common end user and casual solver will spend most of their time. I'm not sure where the regression came from but after this release I would participate in a branch to improve the gui to accept all known formats (sudoku and Sukaku) in addition to extending functionality (for example analyze F9) to include Sukaku which it currently doesn't

**Comment by dobrichev** [comment]
My vote is for supporting all old formats and carefully introducing new ones.
As far as I can understand the issue is in the automatic recognition of the clipboard formats.
My proposal is to revert to old "stable" supported formats, then temporary add into menu "Paste As ..." for each experimental format, and after successful user acceptance append new formats in "auto" parsing engine.

**Comment by SudokuMonster** [comment]
I just tested the Aug 5 release and it only accepts 729-character grids properly. Our current GUI is a modification of that release not a modification on serate 1.2.1. That is possibly where the regression came from

**Comment by SudokuMonster** [comment]
I've added a wiki page with these common formats to test later. I also added wiki pages with puzzles to test command line processing of Vanilla sudoku and sukakus based on serate 1.2.1 and the Sukaku Explainer Aug 5 releases including some bug-exposing puzzles

**Comment by 1to9only** [comment]
As a quick hack, I only meant to support 729-chars sukaku.
` It will paste something from the clipboard when other formats are used but they are not usable.`
Not wanting to spend too much time (then) on the sudoku loading problem, a work around was noted: Selecting 'Tools' from the Menu bar, and clicking on 'Reset potential values'.
I have an idea of a possible fix, but this is based on the old SudokuIO.java code.
I'd leave the current code in, and see if SudokuWiki can provide a fix.

**Comment by 1to9only** [comment]
As an aside, I do have other ideas on SudokuIO.java - just is case you've started similar work!
1. I have ideas on saving sukakus to file in the format:
1st line is 729-chars sukaku,
followed by the pencilmark grid.
2. Revamping the saving of sudoku to file in the last (fancy decorated) format I gave at the beginning.

**Comment by SudokuMonster** [comment]
That's fantastic. When you finish with #15 we can finalize v1.2.1.6 release from the Master branch. I will then create a GUI branch based on the Master branch for us to improve and test

**Comment by sudokuwiki** [comment]
My changeset from yesterday would have fixed that, but @dobrichev reverted it for no real reason.
If you restore that change you can parse all those things.

**Comment by dobrichev** [comment]
@sudokuwiki, do you really don't understand the reason for my reverts?
Please, read some basic instructions for using common repository, fork this project into your own space, experiment there, and when ready propose a pull request to this master.
I promise not to pollute master in the time between your pull request proposal and its rejection/confirmation.

**Comment by 1to9only** [comment]
Can someone point me to a working version (revision) of the file?
Else I'm likely going to test each revision of the SudokuIO.java source.
I don't really want to do this, as it will stop me doing something else. ;)

**Comment by dobrichev** [comment]
According to @sudokuwiki [this](https://github.com/SudokuMonster/SukakuExplainer/commit/ac0215fb52ef8bdee723327e2c0e7683c351c7f1) revision contains working code. I don't know whether it is true and how it interferes with other code changes.

**Comment by SudokuMonster** [comment]
All work on this issue will be done from the branch GUI which will be created after the 1.2.1.6 release which is ready to be done from Master branch now Let the games begin!!!

**Comment by SudokuMonster** [comment]
I deleted the branch GUI after merging with Master. I’m guessing that @1to9only and  @sudokuwiki will start their own branches to do their own work?

**Comment by 1to9only** [comment]
I cannot build anything in 64-bit windows and jdk-12, not even SukakuExpainer-Serate!
There are several errors when compiling the Applet code - [deprecation], [rawtypes], [unchecked].
Presently, I do not have the time to look into fixing these.

**Comment by dobrichev** [comment]
Switching back to java 8 could be an option

**Comment by 1to9only** [comment]
I get the same (or similar!) errors when building SukakuExpainer-Serate with jdk-8.
I've had this when I first compiled SE (last year!), I think this is due to some Java language change introduced in java 1.7 (jdk-7) for JComboBox.
I think that's why I've always compiled my SEs with jdk-6. The jars run on jdk-8.

**Comment by dobrichev** [comment]
I do compile with 1.8. The master has only ~10 warnings. Not the Oracle java but

> OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by 1to9only** [comment]
A quick build and single run of @sudokuwiki commit `https://github.com/SudokuMonster/SukakuExplainer/commit/ac0215fb52ef8bdee723327e2c0e7683c351c7f1` shows it loads all the grids in the issue I raised `https://github.com/SudokuMonster/SukakuExplainer/issues/17#issue-481788308`
So we have a working solution, it should be merged back into master - this may cause other issues.
I plan no further work on this issue.

**Comment by sudokuwiki** [comment]
@dobrichev here is the new file for parsing: https://pastebin.com/NuzKvdEt
Used the latest master file and tested it.
Can someone merge this in the master?

**Comment by SudokuMonster** [comment]
Hi @sudokuwiki I can do that tonight. Will do a quick test and merge. Thanks

**Comment by SudokuMonster** [comment]
@sudokuwiki I tested the Loader on all examples on:

[https://github.com/SudokuMonster/SukakuExplainer/wiki/Vanilla-sudoku-grids-(several-formats)-for-testing](url)

[https://github.com/SudokuMonster/SukakuExplainer/wiki/Loading-Pencilmark-grids-into-Sukaku-explainer-(Test-Puzzles)](url)

All loaded perfectly so should be able to merge with Master directly ...

I'll do that at some stage tonight.

If it compiles correctly then I will be issuing the release v1.3.0.0
