### ISSUE TITLE
batch mode export format

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#19]
As an aside, I do have other ideas on SudokuIO.java - just is case you've started similar work!
1. I have ideas on saving sukakus to file in the format:
1st line is 729-chars sukaku,
followed by the pencilmark grid.
2. Revamping the saving of sudoku to file in the last (fancy decorated) format I gave at the beginning.

_Originally posted by @1to9only in https://github.com/SudokuMonster/SukakuExplainer/issues/17#issuecomment-522178904_

**Comment by dobrichev** [comment]
Look at [this diff](https://github.com/SudokuMonster/SukakuExplainer/commit/b5287a7bac31f3f7c69b8787297039574636003b#diff-e1a5cd219fb57cfdd48a5cc50b89638b) for proposed output format changes.
Focus on System.err.println lines, namely -a, -b, %h, %m, %M, %s, -t

**Comment by 1to9only** [comment]
I think you're talking about something else. I'll look at your changes later.

The present GUI has a 'Save...' option that saves the current state of the sudoku in a file in 9x9 format.
My idea is to split this to:
```
Save Sudoku...   Ctrl-S
Save Sukaku...   Ctrl-U
```
I propose saving the sudoku 'in the last (fancy decorated) format I gave at the beginning' of issue #17.
The sukaku would be saved in 729-chars format followed by the pencilmarks format.
Some code would have been reused from the sukaku pencilmarks code.

**Comment by dobrichev** [comment]
After some parametrization now the behaviour of "pencilmarks" entry pint is emulated by "serate" entry point when run with these parameters:
```
java -Xrs -Xmx1g -cp SukakuExplainer.jar diuf.sudoku.test.serate --format="ED=%r/%p/%d" --start="%g" --before="%M" --after="%i %r, %s" --input=puzzles.txt --output=- --threads=0 > ratedPuzzles.txt
```
This essentially makes the entry points "pencilmarks" and "hints" obsolete. Also the "Tester" entry point (who uses it?).
Soon I will be ready for merging into master.

**Comment by 1to9only** [comment]
I've seen output from Tester posted in forum.enjoysudoku.com going back as far as 2007.

**Comment by dobrichev** [comment]
Thanks. I am not going to erase nor disable the existing code so far.

I created a wiki page [Batch mode command line parameters](https://github.com/SudokuMonster/SukakuExplainer/wiki/Batch-mode-command-line-parameters) with an example demonstrating the whole supported format.
Sanity tests passed.
I am ready for merging to master.

**Comment by SudokuMonster** [comment]
I'm ready too for merging … however I haven't done a pull request before.

**Comment by dobrichev** [comment]
Pull request isn't a must. If you have write credentials to a repository you can use your git client to do the same.
I found the pull requests in the web interface useful because they listed the changed files and it is easy to browse the differences.

**Comment by SudokuMonster** [comment]
I also thought that it would be a good idea to discuss before merging or check for objections/comments, as all documentation available to review by all

**Comment by dobrichev** [comment]
I agree. Unfortunately I can't do any meaningful in reviewing your commit.

**Comment by dobrichev** [comment]
Done and merged to master. Closing.
