### ISSUE TITLE
Align branches with Master

### ISSUE THREAD

**Issue by SudokuMonster** [SudokuMonster/SukakuExplainer#20]
Just to make you aware that batchformatting is behind Master by 2 commits. This likely the result of creating the branch prior to release

**Comment by dobrichev** [comment]
No problem there. I branched intentionally to keep track on my own work. Before merging to the master I will align to it, asking from you for no new commits in master for a while.

**Comment by SudokuMonster** [comment]
That is the idea. No commits direct to Master now as we now (sort of) a functional and presentable release. All my work will be on branches and can be merged following a pull request only after discussion. I think this is what all of us should do now!
