### ISSUE TITLE
Move cell values and potentials to grid

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#26]
- Add tables with cell values and potentials to grid.
- Remove value and potentials from cell.
- Modify existing code to use new data model.
Work in griddata branch.

**Comment by 1to9only** [comment]
Why? Is the intention to speed up SkE? And I think there's a bit of code changes needed?

**Comment by dobrichev** [comment]
yes, and yes

**Comment by 1to9only** [comment]
Good Luck. ;)
It would be interesting to see what speed gains are made.
In the past, I have tried implementing bit lookup tables for BitSet - but there is 64KB size limit for java code blocks, so small tables may be ok, but it didn't like big tables,, e.g. for cardinality(). The work was abandoned.

**Comment by SudokuMonster** [comment]
Hi @dobrichev ,
I'll be updatinf sudokuIO.java with the dirtyfix only in the part that GUI is involved handling multi-line sukaku input. I tested it with current Master without issues. It also shouldn't conflict on your work with the same file in the branch griddata
