### ISSUE TITLE
Sukaku Explainer releases - should build be using JDK-8?

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#30]
I think @SudokuMonster runs jdk-12 on Windows(?), @dobrichev runs openjdk-8u212-b03 on ubuntu, and I can run oracle jdk-8u221 or openjdk-8u221-b10 on win7, 32bit is default, 64bit if needed, and ubuntu if really needed.

1. I could download and run the 1.2.1.4 release, but not the 1.2.1.6.1 release, meaning users downloading a jdk-12 built release may have to upgrade their jre to jre-12.
2. The java Applet class was deprecated in jdk-9, and is likely to disappear in a future jdk release. So building with jdk-9 and newer jdks currently gives a warning message.
3. The jdk-12 built release will also put up a warning in the java console of 'An illegal reflective access operation has occurred' in constructor com.sun.java.swing.plaf.motif.MotifLookAndFeel(). I'm not sure if this will cause further problems with future jdk releases.

Should we 'standardise' on jdk-8? Will @SudokuMonster want to 'downgrade' to jdk-8?
Open for comments.

**Comment by SudokuMonster** [comment]
If everybody thinks that it is a good idea. Tell me how. I’m using Windows with latest jdk aand jre. Compiling using eclipse!!

I’ve compiled directly before but this is good as it gives a pre compile idea if things are going to work or not!!!

**Comment by SudokuMonster** [comment]
I downloaded Java SE 8u221 in addition to selecting the 1.8 Java compliance.
That means that any future release jre will be built using JDK8

**Comment by 1to9only** [comment]
[I've left this project, so cannot create branches anymore.]
The jdk-8 builds with warning errors, I've fixed these in my private build. If you've not already fixed them in this SukakuExplainer, I'll post the fixes here to be applied.

**Comment by dobrichev** [comment]
Nice. My preferred format is scanned images of punch cards. In colors.

**Comment by SudokuMonster** [comment]
I like the humour. I guess this is what happens when you’re working on a project with other people

**Comment by dobrichev** [comment]
Yes. I hope that @1to9only realized from the beginning that this project has no budget. He did several significant contributions and we must thank him for that.
Thank you, @1to9only ! Hope soon you will be back.

**Comment by dobrichev** [comment]
The -Xperf option stopped working on my virtual machine.
It worked before, now silently ignores the command.
Could be related to
```java
import java.util.regex.Matcher;
```
in SudokuIO.java file - regex isn't ancient technology in Java. I can't find any useful info on internet on that topic.
The parameter
`-agentlib:hprof=cpu=samples,depth=100,interval=5,lineno=y,thread=y`
still works. -Xperf still works when our jar file isn't involved. For example
`java -Xprof -X`
lists -X options as expected, and then dumps the execution profile as expected.

**Comment by SudokuMonster** [comment]
Master compiled successfully under JDK8 with warnings

```
Description	Resource	Path	Location	Type
The import java.util is never used	Cell.java	/SukakuExplainer/diuf/sudoku	line 8	Java Problem
The value of the local variable cl is not used	Grid.java	/SukakuExplainer/diuf/sudoku	line 361	Java Problem
Type safety: Unchecked cast from Class[] to Class<? extends Grid.Region>[]	Grid.java	/SukakuExplainer/diuf/sudoku	line 178	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	GenerateDialog.java	/SukakuExplainer/diuf/sudoku/gui	line 693	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	GenerateDialog.java	/SukakuExplainer/diuf/sudoku/gui	line 693	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	SudokuFrame.java	/SukakuExplainer/diuf/sudoku/gui	line 63	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	SudokuFrame.java	/SukakuExplainer/diuf/sudoku/gui	line 689	Java Problem
JComboBox is a raw type. References to generic type JComboBox<E> should be parameterized	SudokuFrame.java	/SukakuExplainer/diuf/sudoku/gui	line 691	Java Problem
Type safety: The method addItem(Object) belongs to the raw type JComboBox. References to generic type JComboBox<E> should be parameterized	GenerateDialog.java	/SukakuExplainer/diuf/sudoku/gui	line 695	Java Problem
Type safety: The method addItem(Object) belongs to the raw type JComboBox. References to generic type JComboBox<E> should be parameterized	SudokuFrame.java	/SukakuExplainer/diuf/sudoku/gui	line 249	Java Problem
Type safety: Unchecked cast from Collection<capture#12-of ?> to Collection<Cell>	CellSet.java	/SukakuExplainer/diuf/sudoku/tools	line 135	Java Problem
Type safety: Unchecked cast from Collection<capture#6-of ?> to Collection<Cell>	CellSet.java	/SukakuExplainer/diuf/sudoku/tools	line 88	Java Problem
Type safety: Unchecked cast from Collection<capture#9-of ?> to Collection<Cell>	CellSet.java	/SukakuExplainer/diuf/sudoku/tools	line 123	Java Problem
```

**Comment by dobrichev** [comment]
JComboBox code is as it is given in the example usages in the Oracle help for JDK 8. I am not sure whether this should be fixed.

Unchecked cast warnings in some internet examples are fixed by suppressing the warning which isn't OK for me. Some help is welcome.

Unused import and variable came from my changes, I'll fix them.

**Comment by dobrichev** [comment]
Warning were fixed.
If we have consensus sticking (for now) to JDK 8 this issue can be closed.

**Comment by SudokuMonster** [comment]
Yes we have
