### ISSUE TITLE
Version strings inconsistency

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#34]
After updating version to 1.3.0 the following
`java -cp /home/mladen/git/SukakuExplainer/SukakuExplainer.jar diuf.sudoku.test.serate -V`
returns
`1.2.1.7`

**Comment by SudokuMonster** [comment]
Yet another  version change that has to be checked (will add to wiki page):

In serate.java
```
18:     static String VERSION = "1.2.1.7";
```

**Comment by dobrichev** [comment]
No. Wait for a while.
VERSION was previously used by both -V and --man invocations.
Should move it in a single place (possibly in Settings.java which is seen from everywhere) and change code to take it from there.

**Comment by SudokuMonster** [comment]
I think I fixed it now

**Comment by dobrichev** [comment]
Yes, it is fixed. Closing.
