### ISSUE TITLE
Experimental ratings change

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#37]
This is related to [branch Experimental-Rating-Don't-Merge](https://github.com/SudokuMonster/SukakuExplainer/tree/Experimental-Rating-Don't-Merge).
I've added details in the wiki page [Difficulty ratings in Sudoku Explainer v1.2.1](https://github.com/SudokuMonster/SukakuExplainer/wiki/Difficulty-ratings-in-Sudoku-Explainer-v1.2.1)

Presently calculation of the rating is spread over many methods and is difficult to follow.
Before doing ad-hock changes, we may
- verify if the details in the wiki page represent the actual rating
- consolidate the rating parameters in a table
- do experiments by modifying the table.

I realize the underlining stuff is complicated, but if we want non-dirty patches, part of the above should be done soon or later.

Comments on correctness of the rating details wiki page are welcome.

**Comment by dobrichev** [comment]
@SudokuMonster I hope the cosmetic changes I've made in master don't interfere with your work.
Added a draft excel table with rules in doc directory.

**Comment by SudokuMonster** [comment]
I’ll look into it. At 1st glance shouldn't be a problem

**Comment by SudokuMonster** [comment]
@dorichev the latest exchanges on the [http://forum.enjoysudoku.com/revision-of-se-ratings-and-resolution-rules-t36376-15.html](url) discussion were interesting!

**Comment by dobrichev** [comment]
After removal of branch "Experimental-Rating-Don't-Merge" this topic is obsolete. Progress has been done in rating changes and modifications were merged to master. The table with techniques and ratings is still an open issue. Closing.
