### ISSUE TITLE
Invocation commands check

### ISSUE THREAD

**Issue by SudokuMonster** [SudokuMonster/SukakuExplainer#5]
The invocation for command line entry point to process sukaku needs checking:

.serate: is only for vanilla sudokus or will it also rate sukaku? (I may have got that wrong)

.hints: displays the next hint with ER/EP/ED rating of Sukaku

.pencilmarks: Displays a pencilmark grid from 729 character string

**Comment by dobrichev** [comment]
Actually serate entry is a dirty patch in test directory made for the Patterns game.
hints and pencilmarks are dirty patches made on top of serate.
To me these entry points are a temporary solution and must be unified in the future.

A possible unification is to leave the GUI entry point default (as it is) and use a single additional entry point (say serate) where additional options are specified by parameters.

I asked 1to9only for dumping the pencilmarks prior to any hint cycle and that is how "hints" entry point was born. Idea was starting from non-minimal partially solved puzzle when debugging. With its current format this doesn't work but is easy to fix. Later I found there are bigger show stoppers.

**Comment by SudokuMonster** [comment]
Fair enough … 

As it stands there are 2 entry points which are yet to merge with serate: .pencilmarks and .hints
1to9only has released a version prior to establishing the repository and detailed the invocation commands on the players forum. I'm assuming this dirty version should include these 2 entry points until they are merged in a future cleaner release. I'll keep this issue open for now and will close another issue that targets part of what we are discussing here.

**Comment by SudokuMonster** [comment]
At this point this version has both .hints and .pencilmarks available as of the Aug 5 release
