### ISSUE TITLE
Java command options Invocation

### ISSUE THREAD

**Issue by SudokuMonster** [SudokuMonster/SukakuExplainer#6]
java.exe -Xrs -Xmx1g -cp or java.exe -Xrs -Xmx500m -cp?

**Comment by dobrichev** [comment]
Batch processing so far doesn't crash with -Xmx500m even after doing a full cycle with no hints found.
For GUI I have no idea.
For the temporary branches I use -Xmx2g or more, so don't expect more meaningful input from me until the eventual stabilization of the changes and merging them into the master.

**Comment by SudokuMonster** [comment]
So it can vary from one user to the other and possibly can be machine dependent! I may then keep it as -Xmx500m as it suits most users. Anybody with knowledge about what the options mean can then experiment!
