### ISSUE TITLE
No pencilmarks file

### ISSUE THREAD

**Issue by SudokuMonster** [SudokuMonster/SukakuExplainer#7]
I couldn't find the pencilmark file in test folder. this a file that was on one of 1to9only's versions:
http://forum.enjoysudoku.com/help-with-sudoku-explainer-t6677-64.html

**Comment by dobrichev** [comment]
Do you mean _SukakuExplainer/diuf/sudoku/test/_ folder?
Test code goes here, not test cases.
In fact, the project has no folder for test cases.

**Comment by SudokuMonster** [comment]
I was referring to the .pencilmark entry point that you mentioned in a differnt issue reply. I'll close this issue to avoid repitition.
