### ISSUE TITLE
Options -> Look & Feel - items keep adding on Variant select/deselect

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#74]
Possible fix:
On SudokuFrame initialization: call initialize(true)
On Variant select/deselect: call initialize(false)
Modify initialize() with true/false argument

**Comment by SudokuMonster** [comment]
Thanks. Well spotted. Problem fixed using your suggestion. It would have also happened on select/deselect of New Rating scheme and SE121 mode from the option menu. All now fixed
