### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#79]
For some time, I've changed the UI for personal taste, e.g. I diskile the vanilla sudoku light turquoise blocks background color and the red region highlight! I tend to change other things on every private builds:
- softer colors, less distractions
- revert some to old SE 1.2.1.3 colors
- focus is on displayed hint

The UI currently look like this:
![Skyscraper](https://user-images.githubusercontent.com/53971101/71411108-f1381100-263f-11ea-918f-ca3ba266f7ac.jpg)

This new UI may not be everyone's cup of tea! So it can be discussed here. If there is consensus, I'll upload the code.
It's OK if the answer is no (issue can be closed), as I'm happy to carry on with my private builds.
Merry Xmas all.

**Comment by 1to9only** [comment]
Another view:
![Skyscraper2](https://user-images.githubusercontent.com/53971101/71411775-a8358c00-2642-11ea-8540-ba3ae7ec285e.jpg)

**Comment by 1to9only** [comment]
What the vanilla sudoku looks like:
![Vanilla](https://user-images.githubusercontent.com/53971101/71411994-7cff6c80-2643-11ea-9ff0-a60711ef5a96.jpg)

**Comment by SudokuMonster** [comment]
To be honest 1to9only I would prefer a consensus on this as some of the changes are not my personal preference but I can't say no either (Not my project alone) …
I like the softer background colours for DG but I actually like that light turquoise blocks background color and the red region highlight! I feel that it added a bit fresher look with the new font as well.

Will post the colour suggestions on the forum and await reply … We could even have several UI preferences (yours and mine) … a bit more coding but should cater for everybody

**Comment by 1to9only** [comment]
Just going by @SudokuMonster's comments above, I'm more likely to not proceed with this, as I'm OK going with my private builds. I don't want the situation reversed! where these changes are made, and others have to reverse them to suit...

**Comment by SudokuMonster** [comment]
Can't you have your own entry in the Look & Feel menu? With a bit of coding your preference would be always their to appear by a menu selection! I think you (and probably me) deserve a bit of immortality for all the work we put in it. The UI changes would cost very little in terms of overall performance. I can't see why even without having a consensus) we couldn't add another option in the Look & feel menu with all preferences that you would like to see!

**Comment by 1to9only** [comment]
From #84, the setGrid change:
`engine.setGrid(sudokuPanel.getSudokuGrid());`
would have been a pre-requisite.
The comment from #84:
`I would still for the time being keep the grid clearing with every variant change & some options selection as referencing a problem or solving technique would be easier.`
means the UI changes are unlikely to happen.
Closed.

**Comment by SudokuMonster** [comment]
I still can't see why we couldn't have different themes / colour change preferences as GUI options. I'm guessing you have looked into that and found it either tricky or in conflict with some of what I mentioned before. I haven't investigated this so I'm not sure what the problem is! I'm happy to look into this again if needed!

**Comment by SudokuMonster** [comment]
With the ability to load() and save() tested and working. I can't see why we couldn't have a theme with panel preferences which can be selected from a themes (sub)menu. The Theme preferences defaults would be in Settings & can be accessed via Settings.getInstance()
