### ISSUE TITLE
GUI fixes

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#8]
The GUI is broken. Update sources to level released at: http://forum.enjoysudoku.com/post280335.html#p280335

**Comment by SudokuMonster** [comment]
I've updated the 2 files in to Aug 5 release. anymore to update?

**Comment by dobrichev** [comment]
It is good the master to be kept in consistent and working state.
Merging the files from branch parallelChaining to master is my duty. Be bold and update until the stability of the master meets 1to9only's expectations. After the testing add a "release" by setting a (lightweight?) tag with the version number and by adding a jar file that corresponds to the master branch at this point.

Few word on my work on parallelChaining branch.
I did (a suboptimal) parallelization of the process affecting the nested chaining (level 4). On 4-core machine it halves the running time for the hardest vanilla puzzles.
I broke the circular reference Cell <-> Grid by removing "grid" property of the Cell.
Few adjustments in object comparison were done.
I did several attempts in introducing new degree of chaining that wouldn't affect old vanilla ratings. At the moment the 4-th hardest sukaku has elimination "C1.7 causes H8.3 both on & off" with rating 12.8, level 4+1. First pass took 150 minutes CPU time and found the elimination, next pass at minute 300 found no more eliminations, and now on minute 1150 the first pass level 4+2 is still in progress.
Also the sorting of the hints was improved saving several minutes per puzzle for the hardest vanilla.
The latest version is committed in the branch but I consider code as unstable and not ready for merging into master.

**Comment by dobrichev** [comment]
BTW https://github.com/SudokuMonster/SukakuExplainer/invitations redirects me to https://github.com/SudokuMonster/SukakuExplainer.

**Comment by sudokuwiki** [comment]
Here is my paste tweak https://pastebin.com/DEQhrMri
It should parse most formats.

**Comment by sudokuwiki** [comment]
Parsing in gui is now working.
solver.getPencilMarks(); seems not merged, test project won't compile.

**Comment by SudokuMonster** [comment]
I uploaded solver.java from the Aug 5 update replacing file in Master which dobrichev may have modified

**Comment by SudokuMonster** [comment]
I'm hoping now that All is fixed now … what is left is a small difference between the current chaining.java and what 1to9only has in the Aug 5 update. We have a mini-release ready now!
I will close this issue soon

**Comment by 1to9only** [comment]
I have not tried building the latest (today's) code on my machine. Had some problems with code from a few days ago. 
The Chaining.java and ChainingHint.java changes in my Aug 5 release do speed up the processing of chains, I thought it would have helped with the tarek 11 sukakus. Try rating a few 10.x and 11.x puzzles without the changes and then with - you might get a pleasant surprise!

**Comment by dobrichev** [comment]
**1to9only**, can you point to "version before" and "version after" the changes that accelerated the chaining?
I need a closeup view because I also make changes there.

**Comment by 1to9only** [comment]
version before: this is the SE 1.2.1 source.
version after: in the source package i put out on Aug 5.

I've also described the changes in the 'Speeding up Sudoku Explainer' thread, post #2. Many of the changes are commenting out code that are not needed.

**Comment by dobrichev** [comment]
Thank you. I doubted you did much more changes.
Isn't removal of
```java
if (length >= 1) // Seems this can be removed!
```
and
```java
if (!isParent(p, pOff)) { // Why this filter? (seems useless)
```
a bit speculative?

**Comment by 1to9only** [comment]
The changes remove redundant code, thus speeding the serate rating process - the modified SE produce exactly the same serate rating as the 1.2.1.3 SE used in the patterns game.

**Comment by dobrichev** [comment]
OK, I am confirming that removal of these lines doesn't affect the rating.

**Comment by SudokuMonster** [comment]
This issue should be closed as the GUI is not broken anymore. The compatibility issue should cover any points raised or alternatively should be raised in a specific issue
