### ISSUE TITLE
How can I compile the source code?

### ISSUE THREAD

**Issue by anonymous7002** [SudokuMonster/SukakuExplainer#83]
How can I compile the source code?
I tried using Eclipse, opening .jardesc file, but it threw many errors.
It created a .jar file, but it didn't open.

**Comment by SudokuMonster** [comment]
Hi anonymous7002,
We use the jdk library 1.8.0_221 to make the compilation compatible with most editions
If that is your JRE system library in Eclipse then it should compile without warnings or errors

**Comment by anonymous7002** [comment]
I checked the preferences, and now it says "The selected JRE does not support the current compiler compliance level of 13".

**Comment by anonymous7002** [comment]
isToroidal cannot be resolved or is not a field

**Comment by SudokuMonster** [comment]
It should work now. As the repository is constantly updated, I wouldn't advise compiling it as there could be missing files, bugs or updates. Safer to wait for a release. Or download the zip file with the latest release which contains the most stable last repository which compiled into the latest release successfully
