### ISSUE TITLE
Latest branch error

### ISSUE THREAD

**Issue by anonymous7002** [SudokuMonster/SukakuExplainer#86]
Latest master branch error:

Solver.java, rows 148-151:

if (Settings.getInstance().whichNC() > 0) {
	addIfWorth(SolvingTechnique.forcingCellNC, directHintProducers, new forcingCellNC());
	addIfWorth(SolvingTechnique.lockedNC, directHintProducers, new lockedNC());
}

forcingCellNC cannot be resolved to a type
lockedNC cannot be resolved to a type

**Comment by anonymous7002** [comment]
Also in current master.

**Comment by SudokuMonster** [comment]
I just downloaded the current Master repository (v1.15.7)
It compiled without errors or warnings.

**Comment by anonymous7002** [comment]
I'm using Eclipse IDE for Java Developers - 2019-12, and jdk-1.8.0_221.

**Comment by SudokuMonster** [comment]
That is what I'm using! I have no idea what's going on to explain this discrepancy.

Can you do a clean download of the Master branch to compile? (so delete your local copy 1st).

This will guarantee that your files are all up to date

**Comment by anonymous7002** [comment]
I did. No help.

**Comment by SudokuMonster** [comment]
As I have the same IDE and same library which compiled without Errors or warnings, I can't suggest anything else to advance this.
I'm planning a release within the next 24-48h which should have an executable.

**Comment by SudokuMonster** [comment]
Nothing fancy.
https://github.com/SudokuMonster/SukakuExplainer
with the branch stating: Master
Green button "download or clone" then download zip which downloads the current Master branch

**Comment by SudokuMonster** [comment]
anonymous7002, as 1to9only compiled the repository without errors too, I would suggest deleting any local copy you have and delete as well from the IDE menu. Download the latest stable Master, Import again to IDE and compile using the same library suggested to you.

**Comment by anonymous7002** [comment]
No worries, the master was updated, it works now.
