### ISSUE TITLE
Compile question

### ISSUE THREAD

**Issue by anonymous7002** [SudokuMonster/SukakuExplainer#88]
I currently compile with jdk1.8.0_221.
Does jdk1.8.0_231 work?

**Comment by 1to9only** [comment]
I don't use IDE, and have just tested (with no problem) compiling (from command line) and running using:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
```
I tend to use oracle's 1.8.0_221.

**Comment by SudokuMonster** [comment]
I would suggest using the same Library to guarantee same compile environment!

**Comment by anonymous7002** [comment]
The only removal of jdk1.8.0_231 compared to jdk1.8.0_221 is:
Removal of T2K Rasterizer and ICU Layout Engine From JavaFX
Does it mean anything to SukakuExplainer?

**Comment by anonymous7002** [comment]
Have you ever experienced issues with 231?

**Comment by 1to9only** [comment]
I just retrieved the java jdk-8u231 for windows from the oracle web site.
java.exe -version:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode)
```
I have tested (with no problem) compiling (from command line) and running using the above.
