### ISSUE TITLE
wiki pages

### ISSUE THREAD

**Issue by dobrichev** [SudokuMonster/SukakuExplainer#9]
If we create wiki pages the structure can include
- general description of the project from users perspective
- solving techniques (start from copy/paste of existing materials, later do some unification of the format)
- list of references to related projects with notes which of their functionalities are implemented here
- release notes
- known issues (in the latest release only)

Can we start now?

**Comment by SudokuMonster** [comment]
I've added a provisional homepage. I think it would be a good idea to keep track of your thoughts and what you have done on a page if that helps progressing the main aspect of this project

**Comment by dobrichev** [comment]
I've created wiki page Related Projects and copied there the known sources.

**Comment by SudokuMonster** [comment]
Obviously morer should be added as time progresses
