### ISSUE TITLE
to fix windoku regions highlighting

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#93]
currently hints involving windoku regions display as a group of single cells:
![windoku2](https://user-images.githubusercontent.com/53971101/87024233-bf982900-c1d0-11ea-8adb-4fbebc5ef67a.png)
![windoku1](https://user-images.githubusercontent.com/53971101/87024248-c2931980-c1d0-11ea-889c-34d891bada01.png)

windoku regions to display as a group of multiple cells:
![windoku2a](https://user-images.githubusercontent.com/53971101/87024307-d50d5300-c1d0-11ea-87c6-2fb73d064d7f.png)
![windoku1a](https://user-images.githubusercontent.com/53971101/87024317-d9d20700-c1d0-11ea-8340-fd92a6623a9c.png)

**Comment by SudokuMonster** [comment]
With Irregular shaped regions, it was easier and faster to code it as a group of single cells. They don't appear as nice as a group of multiple cells but it was a compromise with the time constraints.

As I see it this would affect Windoku & the any planned Jigsaw regions in the future. Luckily the other variants do not have this issue.
