### ISSUE TITLE
Solving techniques when switching modes

### ISSUE THREAD

**Issue by newman-iknewit** [SudokuMonster/SukakuExplainer#98]
This isn't a huge problem, but when using the GUI if you switch to 1.2.1 mode and then switch back, the allowed solving techniques remain restricted to the 1.2.1 settings.

Would it be possible to preserve the user settings in this case?

**Comment by SudokuMonster** [comment]
That is indeed annoying as you would expect things to go back to default ... This should be addressed by the next release
Thanks
